# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_QCOM)	+= db1_07c.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= db1_07r.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= db1_09c.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= db1_12c.dtb

# DB1 with CB3 add on board
dtb-$(CONFIG_ARCH_QCOM)	+= db1_cb3_07c.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= db1_cb3_07r.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= db1_cb3_09c.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= db1_cb3_12c.dtb

# development and test
dtb-$(CONFIG_ARCH_QCOM)	+= db1_dev.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
