# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_QCOM)	+= db1_07c.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= db1_07r.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= db1_09c.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= db1_12c.dtb

dtb-$(CONFIG_ARCH_QCOM)	+= db1_dev.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
