#
# Makefile for the ilitek touchscreen drivers.
#

# Each configuration option enables a list of files.

ilitek_touch-objs := \
	ilitek_hall.o \
	ilitek_lim.o \
	ilitek_sensor_test.o \
	ilitek_tool.o \
	ilitek_update.o

obj-$(CONFIG_TOUCHSCREEN_ILITEK)	:=  ilitek_touch.o
